exp:
  expname: chest_50_2m_freq
  expdir: ./checkpoints/
  datadir: ./data/chest_50.pickle

network:
  encoding_type: freq
  num_materials: 2
  feature_dim: 8
  multires: 6
  s_param: 20.0
  alpha1: 3.4
  beta1: 0.1
  alpha2: 5.5
  beta2: 3.5
  num_levels: 14
  level_dim: 2
  base_resolution: 16
  log2_hashmap_size: 19

train:
  epoch: 1000
  n_batch: 1
  n_rays: 1024
  n_samples: 128
  val_n_samples: 128
  val_chunk_size: 1024
  lrate: 0.001
  lrate_gamma: 0.1
  lrate_step: 500
  lambda_reg: 0.01
  resume: False
  perturb: True
  use_freq_reg: True
  tau_start: 2.0
  warmup_iters: 500
  warmup_epochs: 50

log:
  i_eval: 50
  i_save: 50
  use_wandb: False
  wandb_project: neas
  wandb_entity: null
